repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.10 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      # terraform
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
      - id: shellcheck
