name: pre-commit

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - uses: lablabs/setup-tflint@v1
      name: Setup TFLint
      with:
        tflint_version: latest
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - uses: pre-commit/action@v2.0.0
      env:
        VAULT_ADDR: 'http://localhost:8200'
